[2023-05-17T16:46:25.797+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fondue_dag.clustering scheduled__2023-05-15T00:00:00+00:00 [queued]>
[2023-05-17T16:46:25.818+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fondue_dag.clustering scheduled__2023-05-15T00:00:00+00:00 [queued]>
[2023-05-17T16:46:25.819+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-17T16:46:25.846+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): clustering> on 2023-05-15 00:00:00+00:00
[2023-05-17T16:46:25.859+0000] {standard_task_runner.py:57} INFO - Started process 1717 to run task
[2023-05-17T16:46:25.863+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fondue_dag', 'clustering', 'scheduled__2023-05-15T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/fondue_dag.py', '--cfg-path', '/tmp/tmpodh5cy5j']
[2023-05-17T16:46:25.866+0000] {standard_task_runner.py:85} INFO - Job 34: Subtask clustering
[2023-05-17T16:46:25.947+0000] {task_command.py:410} INFO - Running <TaskInstance: fondue_dag.clustering scheduled__2023-05-15T00:00:00+00:00 [running]> on host 8cf8fb9e28f7
[2023-05-17T16:46:26.136+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='Bhuribhat@gmail.com' AIRFLOW_CTX_DAG_OWNER='pras' AIRFLOW_CTX_DAG_ID='fondue_dag' AIRFLOW_CTX_TASK_ID='clustering' AIRFLOW_CTX_EXECUTION_DATE='2023-05-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-15T00:00:00+00:00'
[2023-05-17T16:46:43.915+0000] {logging_mixin.py:149} WARNING - 2023/05/17 16:46:43 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2023-05-17T16:46:48.404+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-05-17T16:46:48.416+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=fondue_dag, task_id=clustering, execution_date=20230515T000000, start_date=20230517T164625, end_date=20230517T164648
[2023-05-17T16:46:48.464+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-05-17T16:46:48.486+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-05-18T04:22:22.808+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-15T00:00:00+00:00/task_id=clustering permission to 509
[2023-05-18T04:22:22.811+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-15T00:00:00+00:00/task_id=clustering permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-15T00:00:00+00:00/task_id=clustering'
[2023-05-18T04:22:22.892+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-15T00:00:00+00:00/task_id=clustering permission to 509
[2023-05-18T04:22:22.895+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-15T00:00:00+00:00/task_id=clustering permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-15T00:00:00+00:00/task_id=clustering'
[2023-05-18T04:22:22.982+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fondue_dag.clustering scheduled__2023-05-15T00:00:00+00:00 [queued]>
[2023-05-18T04:22:23.002+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fondue_dag.clustering scheduled__2023-05-15T00:00:00+00:00 [queued]>
[2023-05-18T04:22:23.007+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-18T04:22:23.078+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): clustering> on 2023-05-15 00:00:00+00:00
[2023-05-18T04:22:23.102+0000] {standard_task_runner.py:57} INFO - Started process 571 to run task
[2023-05-18T04:22:23.121+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fondue_dag', 'clustering', 'scheduled__2023-05-15T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/fondue_dag.py', '--cfg-path', '/tmp/tmp5my0tf7k']
[2023-05-18T04:22:23.124+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask clustering
[2023-05-18T04:22:23.265+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-15T00:00:00+00:00/task_id=clustering permission to 509
[2023-05-18T04:22:23.267+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-15T00:00:00+00:00/task_id=clustering permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-15T00:00:00+00:00/task_id=clustering'
[2023-05-18T04:22:23.278+0000] {task_command.py:410} INFO - Running <TaskInstance: fondue_dag.clustering scheduled__2023-05-15T00:00:00+00:00 [running]> on host b36de7cfc389
[2023-05-18T04:22:23.541+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='Bhuribhat@gmail.com' AIRFLOW_CTX_DAG_OWNER='pras' AIRFLOW_CTX_DAG_ID='fondue_dag' AIRFLOW_CTX_TASK_ID='clustering' AIRFLOW_CTX_EXECUTION_DATE='2023-05-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-15T00:00:00+00:00'
[2023-05-18T04:23:08.431+0000] {logging_mixin.py:149} WARNING - 2023/05/18 04:23:08 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2023-05-18T04:23:16.580+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-05-18T04:23:16.614+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=fondue_dag, task_id=clustering, execution_date=20230515T000000, start_date=20230518T042222, end_date=20230518T042316
[2023-05-18T04:23:16.686+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-05-18T04:23:16.716+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-05-18T07:19:54.685+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-15T00:00:00+00:00/task_id=clustering permission to 509
[2023-05-18T07:19:54.687+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-15T00:00:00+00:00/task_id=clustering permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-15T00:00:00+00:00/task_id=clustering'
[2023-05-18T07:19:54.748+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-15T00:00:00+00:00/task_id=clustering permission to 509
[2023-05-18T07:19:54.751+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-15T00:00:00+00:00/task_id=clustering permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-15T00:00:00+00:00/task_id=clustering'
[2023-05-18T07:19:54.804+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fondue_dag.clustering scheduled__2023-05-15T00:00:00+00:00 [queued]>
[2023-05-18T07:19:54.854+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fondue_dag.clustering scheduled__2023-05-15T00:00:00+00:00 [queued]>
[2023-05-18T07:19:54.861+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-18T07:19:54.920+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): clustering> on 2023-05-15 00:00:00+00:00
[2023-05-18T07:19:54.938+0000] {standard_task_runner.py:57} INFO - Started process 620 to run task
[2023-05-18T07:19:54.956+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fondue_dag', 'clustering', 'scheduled__2023-05-15T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/fondue_dag.py', '--cfg-path', '/tmp/tmpmwuk7b1g']
[2023-05-18T07:19:54.967+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask clustering
[2023-05-18T07:19:55.090+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-15T00:00:00+00:00/task_id=clustering permission to 509
[2023-05-18T07:19:55.091+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-15T00:00:00+00:00/task_id=clustering permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-15T00:00:00+00:00/task_id=clustering'
[2023-05-18T07:19:55.096+0000] {task_command.py:410} INFO - Running <TaskInstance: fondue_dag.clustering scheduled__2023-05-15T00:00:00+00:00 [running]> on host e6cb8527e075
[2023-05-18T07:19:55.247+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='Bhuribhat@gmail.com' AIRFLOW_CTX_DAG_OWNER='pras' AIRFLOW_CTX_DAG_ID='fondue_dag' AIRFLOW_CTX_TASK_ID='clustering' AIRFLOW_CTX_EXECUTION_DATE='2023-05-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-15T00:00:00+00:00'
[2023-05-18T07:20:34.359+0000] {logging_mixin.py:149} WARNING - 2023/05/18 07:20:34 INFO mlflow.tracking.fluent: Experiment with name 'fondue' does not exist. Creating a new experiment.
[2023-05-18T07:20:34.845+0000] {logging_mixin.py:149} WARNING - 2023/05/18 07:20:34 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2023-05-18T07:20:45.115+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-05-18T07:20:45.153+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=fondue_dag, task_id=clustering, execution_date=20230515T000000, start_date=20230518T071954, end_date=20230518T072045
[2023-05-18T07:20:45.286+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-05-18T07:20:45.371+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
