[2023-05-18T04:39:44.703+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fondue_dag.clustering manual__2023-05-18T04:39:23.655651+00:00 [queued]>
[2023-05-18T04:39:44.715+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fondue_dag.clustering manual__2023-05-18T04:39:23.655651+00:00 [queued]>
[2023-05-18T04:39:44.715+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-18T04:39:44.735+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): clustering> on 2023-05-18 04:39:23.655651+00:00
[2023-05-18T04:39:44.742+0000] {standard_task_runner.py:57} INFO - Started process 1724 to run task
[2023-05-18T04:39:44.745+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fondue_dag', 'clustering', 'manual__2023-05-18T04:39:23.655651+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/fondue_dag.py', '--cfg-path', '/tmp/tmp8ud8y2su']
[2023-05-18T04:39:44.747+0000] {standard_task_runner.py:85} INFO - Job 60: Subtask clustering
[2023-05-18T04:39:44.836+0000] {task_command.py:410} INFO - Running <TaskInstance: fondue_dag.clustering manual__2023-05-18T04:39:23.655651+00:00 [running]> on host b36de7cfc389
[2023-05-18T04:39:44.994+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='Bhuribhat@gmail.com' AIRFLOW_CTX_DAG_OWNER='pras' AIRFLOW_CTX_DAG_ID='fondue_dag' AIRFLOW_CTX_TASK_ID='clustering' AIRFLOW_CTX_EXECUTION_DATE='2023-05-18T04:39:23.655651+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-18T04:39:23.655651+00:00'
[2023-05-18T04:39:45.371+0000] {logging_mixin.py:149} WARNING - 2023/05/18 04:39:45 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2023-05-18T04:39:48.971+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-05-18T04:39:48.984+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=fondue_dag, task_id=clustering, execution_date=20230518T043923, start_date=20230518T043944, end_date=20230518T043948
[2023-05-18T04:39:49.056+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-05-18T04:39:49.079+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
