[2023-05-17T16:46:25.835+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fondue_dag.clustering scheduled__2023-05-14T00:00:00+00:00 [queued]>
[2023-05-17T16:46:25.857+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fondue_dag.clustering scheduled__2023-05-14T00:00:00+00:00 [queued]>
[2023-05-17T16:46:25.858+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-17T16:46:25.890+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): clustering> on 2023-05-14 00:00:00+00:00
[2023-05-17T16:46:25.900+0000] {standard_task_runner.py:57} INFO - Started process 1718 to run task
[2023-05-17T16:46:25.904+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fondue_dag', 'clustering', 'scheduled__2023-05-14T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/fondue_dag.py', '--cfg-path', '/tmp/tmpy2yorl6b']
[2023-05-17T16:46:25.907+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask clustering
[2023-05-17T16:46:25.985+0000] {task_command.py:410} INFO - Running <TaskInstance: fondue_dag.clustering scheduled__2023-05-14T00:00:00+00:00 [running]> on host 8cf8fb9e28f7
[2023-05-17T16:46:26.210+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='Bhuribhat@gmail.com' AIRFLOW_CTX_DAG_OWNER='pras' AIRFLOW_CTX_DAG_ID='fondue_dag' AIRFLOW_CTX_TASK_ID='clustering' AIRFLOW_CTX_EXECUTION_DATE='2023-05-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-14T00:00:00+00:00'
[2023-05-17T16:46:43.882+0000] {logging_mixin.py:149} WARNING - 2023/05/17 16:46:43 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2023-05-17T16:46:48.404+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-05-17T16:46:48.417+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=fondue_dag, task_id=clustering, execution_date=20230514T000000, start_date=20230517T164625, end_date=20230517T164648
[2023-05-17T16:46:48.462+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-05-17T16:46:48.485+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-05-18T04:22:23.190+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-14T00:00:00+00:00/task_id=clustering permission to 509
[2023-05-18T04:22:23.191+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-14T00:00:00+00:00/task_id=clustering permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-14T00:00:00+00:00/task_id=clustering'
[2023-05-18T04:22:23.288+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-14T00:00:00+00:00/task_id=clustering permission to 509
[2023-05-18T04:22:23.289+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-14T00:00:00+00:00/task_id=clustering permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-14T00:00:00+00:00/task_id=clustering'
[2023-05-18T04:22:23.337+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fondue_dag.clustering scheduled__2023-05-14T00:00:00+00:00 [queued]>
[2023-05-18T04:22:23.355+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fondue_dag.clustering scheduled__2023-05-14T00:00:00+00:00 [queued]>
[2023-05-18T04:22:23.355+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-18T04:22:23.417+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): clustering> on 2023-05-14 00:00:00+00:00
[2023-05-18T04:22:23.439+0000] {standard_task_runner.py:57} INFO - Started process 573 to run task
[2023-05-18T04:22:23.462+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fondue_dag', 'clustering', 'scheduled__2023-05-14T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/fondue_dag.py', '--cfg-path', '/tmp/tmp6_2h5eey']
[2023-05-18T04:22:23.466+0000] {standard_task_runner.py:85} INFO - Job 34: Subtask clustering
[2023-05-18T04:22:23.589+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-14T00:00:00+00:00/task_id=clustering permission to 509
[2023-05-18T04:22:23.589+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-14T00:00:00+00:00/task_id=clustering permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-14T00:00:00+00:00/task_id=clustering'
[2023-05-18T04:22:23.597+0000] {task_command.py:410} INFO - Running <TaskInstance: fondue_dag.clustering scheduled__2023-05-14T00:00:00+00:00 [running]> on host b36de7cfc389
[2023-05-18T04:22:23.799+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='Bhuribhat@gmail.com' AIRFLOW_CTX_DAG_OWNER='pras' AIRFLOW_CTX_DAG_ID='fondue_dag' AIRFLOW_CTX_TASK_ID='clustering' AIRFLOW_CTX_EXECUTION_DATE='2023-05-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-14T00:00:00+00:00'
[2023-05-18T04:23:07.639+0000] {logging_mixin.py:149} WARNING - 2023/05/18 04:23:07 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2023-05-18T04:23:16.093+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-05-18T04:23:16.127+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=fondue_dag, task_id=clustering, execution_date=20230514T000000, start_date=20230518T042223, end_date=20230518T042316
[2023-05-18T04:23:16.269+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-05-18T04:23:16.349+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
