[2023-05-16T07:35:44.487+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fondue_dag.clean_fondue_data manual__2023-05-16T07:30:28.769700+00:00 [queued]>
[2023-05-16T07:35:44.498+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fondue_dag.clean_fondue_data manual__2023-05-16T07:30:28.769700+00:00 [queued]>
[2023-05-16T07:35:44.499+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 2
[2023-05-16T07:35:44.520+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): clean_fondue_data> on 2023-05-16 07:30:28.769700+00:00
[2023-05-16T07:35:44.528+0000] {standard_task_runner.py:57} INFO - Started process 1956 to run task
[2023-05-16T07:35:44.531+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fondue_dag', 'clean_fondue_data', 'manual__2023-05-16T07:30:28.769700+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/fondue_dag.py', '--cfg-path', '/tmp/tmp6zu7jlxj']
[2023-05-16T07:35:44.533+0000] {standard_task_runner.py:85} INFO - Job 61: Subtask clean_fondue_data
[2023-05-16T07:35:44.591+0000] {task_command.py:410} INFO - Running <TaskInstance: fondue_dag.clean_fondue_data manual__2023-05-16T07:30:28.769700+00:00 [running]> on host a76a3b1a3408
[2023-05-16T07:35:44.680+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='Bhuribhat@gmail.com' AIRFLOW_CTX_DAG_OWNER='pras' AIRFLOW_CTX_DAG_ID='fondue_dag' AIRFLOW_CTX_TASK_ID='clean_fondue_data' AIRFLOW_CTX_EXECUTION_DATE='2023-05-16T07:30:28.769700+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-16T07:30:28.769700+00:00'
[2023-05-16T07:35:44.739+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/clean_data.py", line 39, in clean_data
    df = df.astype({"latitude": float, "longitude": float})
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5799, in astype
    col.astype(dtype=dtype[col_name], copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5815, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 418, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 327, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 591, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1309, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1257, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1201, in astype_nansafe
    return arr.astype(dtype, copy=True)
ValueError: could not convert string to float: "'100.69002'"
[2023-05-16T07:35:44.759+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=fondue_dag, task_id=clean_fondue_data, execution_date=20230516T073028, start_date=20230516T073544, end_date=20230516T073544
[2023-05-16T07:35:44.774+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 61 for task clean_fondue_data (could not convert string to float: "'100.69002'"; 1956)
[2023-05-16T07:35:44.824+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-16T07:35:44.852+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
