[2023-05-16T16:27:26.457+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fondue_dag.visualize_data manual__2023-05-16T16:21:52.594763+00:00 [queued]>
[2023-05-16T16:27:26.468+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fondue_dag.visualize_data manual__2023-05-16T16:21:52.594763+00:00 [queued]>
[2023-05-16T16:27:26.469+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 2
[2023-05-16T16:27:26.486+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): visualize_data> on 2023-05-16 16:21:52.594763+00:00
[2023-05-16T16:27:26.493+0000] {standard_task_runner.py:57} INFO - Started process 4635 to run task
[2023-05-16T16:27:26.495+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fondue_dag', 'visualize_data', 'manual__2023-05-16T16:21:52.594763+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/fondue_dag.py', '--cfg-path', '/tmp/tmpn4gv37xi']
[2023-05-16T16:27:26.498+0000] {standard_task_runner.py:85} INFO - Job 38: Subtask visualize_data
[2023-05-16T16:27:26.548+0000] {task_command.py:410} INFO - Running <TaskInstance: fondue_dag.visualize_data manual__2023-05-16T16:21:52.594763+00:00 [running]> on host 9a20db09badf
[2023-05-16T16:27:26.644+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='Bhuribhat@gmail.com' AIRFLOW_CTX_DAG_OWNER='pras' AIRFLOW_CTX_DAG_ID='fondue_dag' AIRFLOW_CTX_TASK_ID='visualize_data' AIRFLOW_CTX_EXECUTION_DATE='2023-05-16T16:21:52.594763+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-16T16:21:52.594763+00:00'
[2023-05-16T16:27:26.789+0000] {font_manager.py:1352} WARNING - findfont: Font family ['TH Sarabun Chula'] not found. Falling back to DejaVu Sans.
[2023-05-16T16:27:26.801+0000] {font_manager.py:1352} WARNING - findfont: Font family ['TH Sarabun Chula'] not found. Falling back to DejaVu Sans.
[2023-05-16T16:27:27.106+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/visualize.py", line 104, in visualize_data
    compare_pie_plot(df, 'state', None)
  File "/opt/airflow/dags/utils/visualize.py", line 74, in compare_pie_plot
    textprops={'size': 'x-large'}, startangle=90
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2761, in pie
    **({"data": data} if data is not None else {}))
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/__init__.py", line 1414, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 3066, in pie
    raise ValueError("'explode' must be of length 'x'")
ValueError: 'explode' must be of length 'x'
[2023-05-16T16:27:27.124+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=fondue_dag, task_id=visualize_data, execution_date=20230516T162152, start_date=20230516T162726, end_date=20230516T162727
[2023-05-16T16:27:27.140+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 38 for task visualize_data ('explode' must be of length 'x'; 4635)
[2023-05-16T16:27:27.191+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-16T16:27:27.213+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
