[2023-05-17T16:46:19.144+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fondue_dag.clustering scheduled__2023-05-13T00:00:00+00:00 [queued]>
[2023-05-17T16:46:19.164+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fondue_dag.clustering scheduled__2023-05-13T00:00:00+00:00 [queued]>
[2023-05-17T16:46:19.165+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-17T16:46:19.194+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): clustering> on 2023-05-13 00:00:00+00:00
[2023-05-17T16:46:19.209+0000] {standard_task_runner.py:57} INFO - Started process 1207 to run task
[2023-05-17T16:46:19.215+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fondue_dag', 'clustering', 'scheduled__2023-05-13T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/fondue_dag.py', '--cfg-path', '/tmp/tmp84tp014y']
[2023-05-17T16:46:19.218+0000] {standard_task_runner.py:85} INFO - Job 27: Subtask clustering
[2023-05-17T16:46:19.300+0000] {task_command.py:410} INFO - Running <TaskInstance: fondue_dag.clustering scheduled__2023-05-13T00:00:00+00:00 [running]> on host 8cf8fb9e28f7
[2023-05-17T16:46:19.479+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='Bhuribhat@gmail.com' AIRFLOW_CTX_DAG_OWNER='pras' AIRFLOW_CTX_DAG_ID='fondue_dag' AIRFLOW_CTX_TASK_ID='clustering' AIRFLOW_CTX_EXECUTION_DATE='2023-05-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-13T00:00:00+00:00'
[2023-05-17T16:46:21.401+0000] {logging_mixin.py:149} WARNING - 2023/05/17 16:46:21 INFO mlflow.tracking.fluent: Experiment with name 'fondue' does not exist. Creating a new experiment.
[2023-05-17T16:46:21.603+0000] {logging_mixin.py:149} WARNING - 2023/05/17 16:46:21 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2023-05-17T16:46:28.574+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-05-17T16:46:28.605+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=fondue_dag, task_id=clustering, execution_date=20230513T000000, start_date=20230517T164619, end_date=20230517T164628
[2023-05-17T16:46:28.692+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-05-17T16:46:28.745+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-05-18T04:22:23.031+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-13T00:00:00+00:00/task_id=clustering permission to 509
[2023-05-18T04:22:23.033+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-13T00:00:00+00:00/task_id=clustering permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-13T00:00:00+00:00/task_id=clustering'
[2023-05-18T04:22:23.191+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-13T00:00:00+00:00/task_id=clustering permission to 509
[2023-05-18T04:22:23.192+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-13T00:00:00+00:00/task_id=clustering permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-13T00:00:00+00:00/task_id=clustering'
[2023-05-18T04:22:23.245+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fondue_dag.clustering scheduled__2023-05-13T00:00:00+00:00 [queued]>
[2023-05-18T04:22:23.271+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fondue_dag.clustering scheduled__2023-05-13T00:00:00+00:00 [queued]>
[2023-05-18T04:22:23.272+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-18T04:22:23.328+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): clustering> on 2023-05-13 00:00:00+00:00
[2023-05-18T04:22:23.342+0000] {standard_task_runner.py:57} INFO - Started process 572 to run task
[2023-05-18T04:22:23.351+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fondue_dag', 'clustering', 'scheduled__2023-05-13T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/fondue_dag.py', '--cfg-path', '/tmp/tmpoo9uhg9p']
[2023-05-18T04:22:23.354+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask clustering
[2023-05-18T04:22:23.512+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-13T00:00:00+00:00/task_id=clustering permission to 509
[2023-05-18T04:22:23.514+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-13T00:00:00+00:00/task_id=clustering permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=fondue_dag/run_id=scheduled__2023-05-13T00:00:00+00:00/task_id=clustering'
[2023-05-18T04:22:23.519+0000] {task_command.py:410} INFO - Running <TaskInstance: fondue_dag.clustering scheduled__2023-05-13T00:00:00+00:00 [running]> on host b36de7cfc389
[2023-05-18T04:22:23.766+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='Bhuribhat@gmail.com' AIRFLOW_CTX_DAG_OWNER='pras' AIRFLOW_CTX_DAG_ID='fondue_dag' AIRFLOW_CTX_TASK_ID='clustering' AIRFLOW_CTX_EXECUTION_DATE='2023-05-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-13T00:00:00+00:00'
[2023-05-18T04:23:08.371+0000] {logging_mixin.py:149} WARNING - 2023/05/18 04:23:08 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2023-05-18T04:23:16.414+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-05-18T04:23:16.433+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=fondue_dag, task_id=clustering, execution_date=20230513T000000, start_date=20230518T042223, end_date=20230518T042316
[2023-05-18T04:23:16.502+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-05-18T04:23:16.542+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
